export const ADD_TO_CART = 'ADD_TO_CART';
export const CLOSE_CART = 'CLOSE_CART';
export const UPDATE_CART_PRODUCT_QUANTITY = 'UPDATE_CART_PRODUCT_QUANTITY';
export const SETTLE_CART = 'SETTLE_CART';
